### ISSUE TITLE
Create Build

### ISSUE THREAD

**Issue by Akenjeru** [anhbh310/gotify2telegram#3]
I apologize for what may be a stupid question, but do I understand correctly that you just need to take the source files and write make build?
I have a test installation of Ubuntu 22.04 lts, ​​all the files are in one folder and after Make build in the last lines it is

![image](https://github.com/anhbh310/gotify2telegram/assets/38863392/de0e23aa-1d46-456b-94e3-7162456c3f2c)
Yes, this may be stupid, but I will be glad for your help

**Comment by anhbh310** [comment]
Hello @Akenjeru, I've checked the build process and everything still seems alright.

Can I see your go environment by running `go env`, and your `go.mod` file?

Perhaps you should try `go mod tidy` before running `make build`.

I'm glad to see your question. Please let me know if there is anything new.

**Comment by Akenjeru** [comment]
> Hello @Akenjeru, I've checked the build process and everything still seems alright.
> 
> Can I see your go environment by running `go env`, and your `go.mod` file?
> 
> Perhaps you should try `go mod tidy` before running `make build`.
> 
> I'm glad to see your question. Please let me know if there is anything new.

i take git clone from you repo, or i need install gotify build?

**Comment by Akenjeru** [comment]
> Hello @Akenjeru, I've checked the build process and everything still seems alright.
> 
> Can I see your go environment by running `go env`, and your `go.mod` file?
> 
> Perhaps you should try `go mod tidy` before running `make build`.
> 
> I'm glad to see your question. Please let me know if there is anything new.

```
services:
  app:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:80
    environment:
      - TZ='Africa/Casablanca'
    volumes:
      - ./data:/app/data
```

This my docker-compose.yml with gotify server and inside folder i take git clone your repo

![image](https://github.com/anhbh310/gotify2telegram/assets/38863392/25f9f85f-20d2-42e2-b80c-9af8d8df68bc)
this go.mod file
